TilausDB1/Models/Tilaukset.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDB1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilaukset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tilaukset()
        {
            this.Tilausrivit = new HashSet<Tilausrivit>();
        }
    
        public int TilausID { get; set; }
        public int AsiakasID { get; set; }
        public string Toimitusosoite { get; set; }
        public string Postinumero { get; set; }
        public Nullable<System.DateTime> Tilauspvm { get; set; }
        public Nullable<System.DateTime> Toimituspvm { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tilausrivit> Tilausrivit { get; set; }
    }
}

TilausDB1/Controllers/TilauksetController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TilausDB1.Models;
using System.Data;
using System.Data.Entity;

namespace TilausDB1.Controllers
{ 
public class TilauksetController : Controller
    {
        // GET: Tilaukset
        TilausDBEntities2 db = new TilausDBEntities2();


        public ActionResult Index()
        {
            if (Session["Username"] == null)
            {
                return RedirectToAction("login", "home");
            }
            else
            {
                var model = db.Tilaukset.Include(t => t.Asiakkaat).Include(t => t.Postitoimipaikat);
                return View(model.ToList());
            }
        }
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var model = db.Tilaukset.Include(t => t.Asiakkaat).Include(t => t.Postitoimipaikat);
            Tilaukset tilaukset = db.Tilaukset.Find(id);
            if (tilaukset == null) return HttpNotFound();
            ViewBag.AsiakasID = new SelectList(db.Tilaukset, "AsiakasID", "Postinumero", selectedValue: "AsiakasID");
            ViewBag.Postinumero = new SelectList(db.Tilaukset, "AsiakasID", "Postinumero", selectedValue: "Postinumero");
            return View(tilaukset);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Katso https://go.microsoft.com/fwlink/?LinkId=317598
        public ActionResult Edit([Bind(Include = "TilausID,AsiakasID,Toimitusosoite,Tilauspvm,Toimituspvm,Nimi,Postitoimipaikka")] Tilaukset tilaukset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tilaukset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tilaukset);
        }
        public ActionResult _ModalEdit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var model = db.Tilaukset.Include(t => t.Asiakkaat).Include(t => t.Postitoimipaikat);
            Tilaukset tilaukset = db.Tilaukset.Find(id);
            if (tilaukset == null) return HttpNotFound();
            ViewBag.AsiakasID = new SelectList(db.Tilaukset, "AsiakasID", "Postinumero", selectedValue: "AsiakasID");
            ViewBag.Postinumero = new SelectList(db.Tilaukset, "AsiakasID", "Postinumero", selectedValue: "Postinumero");
            return PartialView("_ModalEdit", tilaukset);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Katso https://go.microsoft.com/fwlink/?LinkId=317598
        public ActionResult _ModalEdit([Bind(Include = "TilausID,AsiakasID,Toimitusosoite,Tilauspvm,Toimituspvm,Nimi,Postitoimipaikka")] Tilaukset tilaukset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tilaukset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return PartialView("_ModalEdit", tilaukset);
        }




        public ActionResult Create()
        {
            ViewBag.AsiakasID = new SelectList(db.Asiakkaat,  "AsiakasID", "Nimi");
            ViewBag.Postinumero = new SelectList(db.Postitoimipaikat, "Postinumero", "Postinumero");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Katso https://go.microsoft.com/fwlink/?LinkId=317598
        public ActionResult Create([Bind(Include = "Toimitusosoite,Tilauspvm,Toimituspvm,Nimi,Postinumero,AsiakasID")] Tilaukset tilaukset)
        {
            if (ModelState.IsValid)
            {
                db.Tilaukset.Add(tilaukset);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AsiakasID = new SelectList(db.Asiakkaat, "AsiakasID", "Nimi", tilaukset.AsiakasID);
            ViewBag.Postinumero = new SelectList(db.Postitoimipaikat, "Postinumero", "Postinumero", tilaukset.Postinumero);
            return View(tilaukset);
        }

    }
}

TilausDB1/Controllers/TilauksetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TilausDB1.Models;
using TilausDB1.ViewModels;

namespace TilausDB1.Controllers
{
    public class TilauksetsController : Controller
    {
        private TilausDBEntities2 db = new TilausDBEntities2();

        // GET: Tilauksets
        public ActionResult Index()
        {
            var tilaukset = db.Tilaukset.Include(t => t.Asiakkaat).Include(t => t.Postitoimipaikat);
            return View(tilaukset.ToList());
        }

        // GET: Tilauksets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tilaukset tilaukset = db.Tilaukset.Find(id);
            if (tilaukset == null)
            {
                return HttpNotFound();
            }
            return View(tilaukset);
        }

        // GET: Tilauksets/Create
        public ActionResult Create()
        {
            ViewBag.AsiakasID = new SelectList(db.Asiakkaat, "AsiakasID", "Nimi");
            ViewBag.Postinumero = new SelectList(db.Postitoimipaikat, "Postinumero", "Postitoimipaikka");
            return View();
        }

        // POST: Tilauksets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TilausID,AsiakasID,Toimitusosoite,Postinumero,Tilauspvm,Toimituspvm")] Tilaukset tilaukset)
        {
            if (ModelState.IsValid)
            {
                db.Tilaukset.Add(tilaukset);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AsiakasID = new SelectList(db.Asiakkaat, "AsiakasID", "Nimi", tilaukset.AsiakasID);
            ViewBag.Postinumero = new SelectList(db.Postitoimipaikat, "Postinumero", "Postitoimipaikka", tilaukset.Postinumero);
            return View(tilaukset);
        }

        // GET: Tilauksets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tilaukset tilaukset = db.Tilaukset.Find(id);
            if (tilaukset == null)
            {
                return HttpNotFound();
            }
            ViewBag.AsiakasID = new SelectList(db.Asiakkaat, "AsiakasID", "Nimi", tilaukset.AsiakasID);
            ViewBag.Postinumero = new SelectList(db.Postitoimipaikat, "Postinumero", "Postitoimipaikka", tilaukset.Postinumero);
            return View(tilaukset);
        }

        // POST: Tilauksets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TilausID,AsiakasID,Toimitusosoite,Postinumero,Tilauspvm,Toimituspvm")] Tilaukset tilaukset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tilaukset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AsiakasID = new SelectList(db.Asiakkaat, "AsiakasID", "Nimi", tilaukset.AsiakasID);
            ViewBag.Postinumero = new SelectList(db.Postitoimipaikat, "Postinumero", "Postitoimipaikka", tilaukset.Postinumero);
            return View(tilaukset);
        }

        // GET: Tilauksets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tilaukset tilaukset = db.Tilaukset.Find(id);
            if (tilaukset == null)
            {
                return HttpNotFound();
            }
            return View(tilaukset);
        }

        // POST: Tilauksets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tilaukset tilaukset = db.Tilaukset.Find(id);
            db.Tilaukset.Remove(tilaukset);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Tilaussummary()
        {
            var tilausSummary = from a in db.Asiakkaat
                                join t in db.Tilaukset on a.AsiakasID equals t.AsiakasID
                                //where-lause
                                //orderby-lause
                                select new TilausTietoData
                                {
                                    TilausID = t.TilausID,
                                    AsiakasID = (int)a.AsiakasID,
                                    Tilauspvm = (DateTime)t.Tilauspvm,
                                    Toimituspvm = (DateTime)t.Toimituspvm,
                                    Toimitusosoite = t.Toimitusosoite,
                                    Osoite = a.Osoite,
                                    Postinumero = a.Postinumero,
                                    Nimi = a.Nimi,
                                };

            return View(tilausSummary);
        }

        public ActionResult _TilausRivit(int? orderid)
        {
            var tilausRiviList = from tr in db.Tilausrivit
                                join t in db.Tuotteet on tr.TuoteID equals t.TuoteID
                                 //join k in db.Kategoriat on t.KategoriaId equals k.KategoriaId
                                where tr.TilausID == orderid
                                //orderby-lause
                                select new TilausRivit
                                {
                                    TilausID = tr.TilausriviID,
                                    TuoteID = (int)t.TuoteID,
                                    Ahinta = (decimal)t.Ahinta,
                                    Nimi = t.Nimi,
                                    Kategoria = t.Kategoria,
                                    Maara = (int)tr.Maara

                                };

            return PartialView(tilausRiviList);
        }
    }
}

TilausDB1/Views/Tilaukset/Create.cshtml
@model TilausDB1.Models.Tilaukset

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tilaukset</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.AsiakasID, "AsiakasID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AsiakasID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AsiakasID, "", new { @class = "text-danger" })
        </div>
    </div>
    @*Yritän lisätä tuotteet tilaukseen*@
    @*<div class="form-group">
        @Html.LabelFor(model => model.TuoteID, "TuoteID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TuoteID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AsiakasID, "", new { @class = "text-danger" })
        </div>
    </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.Toimitusosoite, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Toimitusosoite, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Toimitusosoite, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Postinumero, "Postinumero", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Postinumero", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Postinumero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tilauspvm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tilauspvm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tilauspvm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Toimituspvm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Toimituspvm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Toimituspvm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TilausDB1/Views/Tilaukset/Edit.cshtml
@model TilausDB1.Models.Tilaukset

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tilaukset</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TilausID)

    <div class="form-group">
        @Html.LabelFor(model => model.AsiakasID, "AsiakasID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AsiakasID", null, htmlAttributes: new { @class = "form-control", @id = "Category" })
            @Html.ValidationMessageFor(model => model.AsiakasID, "", new { @class = "text-danger" })
        </div>

    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Toimitusosoite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Toimitusosoite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Toimitusosoite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Postinumero, "Postinumero", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Postinumero", null, htmlAttributes: new { @class = "form-control", @id = "Category" })
                @Html.ValidationMessageFor(model => model.Postinumero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tilauspvm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tilauspvm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tilauspvm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Toimituspvm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Toimituspvm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Toimituspvm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TilausDB1/Views/Tilaukset/Index.cshtml
@model IEnumerable<TilausDB1.Models.Tilaukset>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous">


@{
    ViewBag.Title = "Index";
}

@section scripts {
    <script type="text/javascript">
        $(function () {
            $(".getOrderId").click(function () {
                let orderId = $(this).data("orderid");
                console.log("Klikkasit tilausnumeroa: " + orderId);
                var url = "/Tilaukset/_ModalEdit/?id=" + orderId;
                console.log(url);

                $("#orderEdit").append(" <b>Avataan tilauksen " + orderId + " muokkausikkuna...</b>");

                var $detailDivEdit = $("#orderEdit");
                $.get(url, function (data) {
                    $detailDivEdit.replaceWith(data);
                    $('#ModalOrderEdit').modal('show');
                });
            });
        });
    </script>
    }

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div id="orderEdit"></div>
<table class="table">
    <tr>
        <th>Muokkaa</th>
        <th>@Html.DisplayNameFor(model => model.Toimitusosoite)</th>
        <th>@Html.DisplayNameFor(model => model.Tilauspvm)</th>
        <th>@Html.DisplayNameFor(model => model.Toimituspvm)</th>
        <th>@Html.DisplayNameFor(model => model.Asiakkaat.Nimi)</th>
        <th>@Html.DisplayNameFor(model => model.Postitoimipaikat.Postitoimipaikka)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><button class="getOrderId fas fa-edit" data-orderid="@item.TilausID"></button></td>
            <td>@Html.DisplayFor(modelItem => item.Toimitusosoite)</td>
            <td>@Html.DisplayFor(modelItem => item.Tilauspvm)</td>
            <td>@Html.DisplayFor(modelItem => item.Toimituspvm)</td>
            <td>@Html.DisplayFor(modelItem => item.Asiakkaat.Nimi)</td>
            <td>@Html.DisplayFor(modelItem => item.Postitoimipaikat.Postitoimipaikka)</td>
            <td>
                <a class="btn btn-primary" href="~/Tilaukset/Edit/@item.TilausID">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                    </svg>
                </a>
                <a class="btn btn-primary" href="~/Tilaukset/Details/@item.TilausID">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-lg" viewBox="0 0 16 16">
                        <path d="m9.708 6.075-3.024.379-.108.502.595.108c.387.093.464.232.38.619l-.975 4.577c-.255 1.183.14 1.74 1.067 1.74.72 0 1.554-.332 1.933-.789l.116-.549c-.263.232-.65.325-.905.325-.363 0-.494-.255-.402-.704l1.323-6.208Zm.091-2.755a1.32 1.32 0 1 1-2.64 0 1.32 1.32 0 0 1 2.64 0Z" />
                    </svg>
                </a>
                <a class="btn btn-primary" href="~/Tilaukset/Delete/@item.TilausID">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                    </svg>
                </a>
            </td>
        </tr>
    }

</table>

TilausDB1/Views/Tilaukset/_ModalEdit.cshtml
@model TilausDB1.Models.Tilaukset

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

<div class="modal fade" id="ModalOrderEdit">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Muokkaa tilaustietoja</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("_ModalEdit", "Tilaukset", FormMethod.Post, new { id = "editForm" }))
                {
                    @Html.AntiForgeryToken()
                }
                <div class="form-horizontal">
                    <h4>Tilaukset</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.TilausID)
                </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AsiakasID, "AsiakasID", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("AsiakasID", null, htmlAttributes: new { @class = "form-control", @id = "Category" })
                                    @Html.ValidationMessageFor(model => model.AsiakasID, "", new { @class = "text-danger" })
                                </div>

                            </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Toimitusosoite, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Toimitusosoite, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Toimitusosoite, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Postinumero, "Postinumero", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Postinumero", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Postinumero, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        </div>
                        <div class="col-sm-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Tilauspvm, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Tilauspvm, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Tilauspvm, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Toimituspvm, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Toimituspvm, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Toimituspvm, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        </div>
                    </div>
                
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="editForm"><i class="fas fa-check"></i></button>
                <a href="@Url.Action("Index", "Tilaukset")" class="btn btn-primary"><i class="fas fa-times"></i></a>
            </div>
        </div>
    </div>
</div>