TilausDB1/Models/Tuotteet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDB1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuotteet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuotteet()
        {
            this.Tilausrivit = new HashSet<Tilausrivit>();
        }
    
        public int TuoteID { get; set; }
        public string Nimi { get; set; }
        public Nullable<decimal> Ahinta { get; set; }
        public string Kuva { get; set; }
        public Nullable<int> Kategoria { get; set; }
        public string KuvaPath { get; set; }
    
        public virtual Kategoriat Kategoriat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tilausrivit> Tilausrivit { get; set; }
        public virtual Tuotteet Tuotteet1 { get; set; }
        public virtual Tuotteet Tuotteet2 { get; set; }
    }
}

TilausDB1/Controllers/TuotteetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TilausDB1.Models;
using PagedList;

namespace TilausDB1.Controllers
{
    public class TuotteetController : Controller
    {
        // GET: Tuotteet
        TilausDBEntities2 db = new TilausDBEntities2();

        public ActionResult Index(string sortOrder, string currentFilter1, string searchString1, string ProductCategory, string currentProductCategory, int? page, int? pagesize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.ProductNameSortParm = String.IsNullOrEmpty(sortOrder) ? "productname_desc" : "";
            ViewBag.UnitPriceSortParm = sortOrder == "UnitPrice" ? "unitPrice_desc" : "UnitPrice";

            if(searchString1 != null)
            {
                page = 1;
            }
            else
            {
                searchString1 = currentFilter1;
            }

            ViewBag.currentFilter1 = searchString1;

            if ((ProductCategory != null) && (ProductCategory != "0"))
            {
                page = 1;
            }
            else
            {
                ProductCategory = currentProductCategory;
            }
            ViewBag.currentProductCategory = ProductCategory;


            TilausDBEntities2 db = new TilausDBEntities2();
            
            var tuotteet = from t in db.Tuotteet
                           select t;

            if (!String.IsNullOrEmpty(searchString1)) //Jos hakufiltteri on käynnissä, niin käytetään sitä ja sen lisäksi lajitellaan tulokset
            {
                switch (sortOrder)
                {
                    case "productname_desc":
                        tuotteet = tuotteet.Where(t => t.Nimi.Contains(searchString1)).OrderByDescending(t => t.Nimi);
                        break;
                    case "UnitPrice":
                        tuotteet = tuotteet.Where(t => t.Nimi.Contains(searchString1)).OrderBy(t => t.Ahinta);
                        break;
                    case "UnitPrice_desc":
                        tuotteet = tuotteet.Where(t => t.Nimi.Contains(searchString1)).OrderByDescending(t => t.Ahinta);
                        break;
                    default:
                        tuotteet = tuotteet.Where(t => t.Nimi.Contains(searchString1)).OrderBy(t => t.Nimi);
                        break;
                }
            }
            else if (!String.IsNullOrEmpty(ProductCategory) && (ProductCategory != "0"))//Jos käytössä on tuoteryhmärajaus, niin käytetään sitä ja sen lisäksi lajitellaan tulokset
            {
                int para = int.Parse(ProductCategory);
                switch (sortOrder)
                {
                    case "productname_desc":
                        tuotteet = tuotteet.Where(t => t.Kategoria == para).OrderByDescending(t => t.Nimi);
                        break;
                    case "UnitPrice":
                        tuotteet = tuotteet.Where(t => t.Kategoria == para).OrderBy(t => t.Ahinta);
                        break;
                    case "UnitPrice_desc":
                        tuotteet = tuotteet.Where(t => t.Kategoria == para).OrderByDescending(t => t.Ahinta);
                        break;
                    default:
                        tuotteet = tuotteet.Where(t => t.Kategoria == para).OrderBy(t => t.Nimi);
                        break;
                }
            } else{ //Hakufiltteri ei ole käynnissä, joten lajitellaan ilman suodatuksia
                switch (sortOrder)
                {
                    case "productname_desc":
                        tuotteet = tuotteet.OrderByDescending(t => t.Nimi);
                        break;
                    case "UnitPrice":
                        tuotteet = tuotteet.OrderBy(t => t.Ahinta);
                        break;
                    case "UnitPrice_desc":
                        tuotteet = tuotteet.OrderByDescending(t => t.Ahinta);
                        break;
                    default:
                        tuotteet = tuotteet.OrderBy(t => t.Nimi);
                        break;
                }
            };

            List<Kategoriat> lstKategoriat = new List<Kategoriat>();

            var kategoriaList = from kat in db.Kategoriat
                               select kat;

            Kategoriat tyhjaKategoria = new Kategoriat();
            tyhjaKategoria.KategoriaId = 0;
            tyhjaKategoria.KategoriaNimi = "";
            tyhjaKategoria.KategoriaIDKategoriaNimi = "";
            lstKategoriat.Add(tyhjaKategoria);

            foreach (Kategoriat kategoria in kategoriaList)
            {
                Kategoriat yksiKategoria = new Kategoriat();
                yksiKategoria.KategoriaId = kategoria.KategoriaId;
                yksiKategoria.KategoriaNimi = kategoria.KategoriaNimi;
                yksiKategoria.KategoriaIDKategoriaNimi = kategoria.KategoriaId.ToString() + " - " + kategoria.KategoriaNimi;
                lstKategoriat.Add(yksiKategoria);
            }
            ViewBag.CategoryID = new SelectList(lstKategoriat, "KategoriaId", "KategoriaIDKategoriaNimi", ProductCategory);

            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return View(tuotteet.ToPagedList(pageNumber, pageSize));
        }


        //public ActionResult Index3()
        //{
        //    if (Session["Username"] == null)
        //    {
        //        return RedirectToAction("login", "home");
        //    }
        //    else
        //    {
        //        TilausDBEntities2 db = new TilausDBEntities2();
        //        List<Tuotteet> model = db.Tuotteet.ToList();
        //        return View(model);
        //    }
        //}

        public ActionResult Index2()
        {
                TilausDBEntities2 db = new TilausDBEntities2();
                List<Tuotteet> model = db.Tuotteet.ToList();

                return View(model);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Tuotteet tuotteet = db.Tuotteet.Find(id);
            if (tuotteet == null) return HttpNotFound();
            return View(tuotteet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Katso https://go.microsoft.com/fwlink/?LinkId=317598
        public ActionResult Edit([Bind(Include = "TuoteID,Nimi,Ahinta,Kuva")] Tuotteet tuotteet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tuotteet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tuotteet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Katso https://go.microsoft.com/fwlink/?LinkId=317598
        public ActionResult Create([Bind(Include = "TuoteID,Nimi,Ahinta,Kategoria")] Tuotteet tuotteet)
        {
            if (ModelState.IsValid)
            {
                db.Tuotteet.Add(tuotteet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tuotteet);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Tuotteet tuotteet = db.Tuotteet.Find(id);
            if (tuotteet == null) return HttpNotFound();
            return View(tuotteet);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tuotteet tuotteet = db.Tuotteet.Find(id);
            db.Tuotteet.Remove(tuotteet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TilausDB1/Views/Tuotteet/Create.cshtml
@model TilausDB1.Models.Tuotteet

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tuotteet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nimi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nimi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nimi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ahinta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ahinta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ahinta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kuva, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Kuva, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kuva, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Kategoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Kategoria, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kategoria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TilausDB1/Views/Tuotteet/Delete.cshtml
@model TilausDB1.Models.Tuotteet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tuotteet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ahinta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ahinta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kuva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kuva)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <svg class="bi bi-x-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd" />
<path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 010 .708l-7 7a.5.5 0 01-.708-.708l7-7a.5.5 0 01.708 0z" clip-rule="evenodd" />
<path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 000 .708l7 7a.5.5 0 00.708-.708l-7-7a.5.5 0 00-.708 0z" clip-rule="evenodd" />
</svg>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TilausDB1/Views/Tuotteet/Edit.cshtml
@model TilausDB1.Models.Tuotteet

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tuotteet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TuoteID)

    <div class="form-group">
        @Html.LabelFor(model => model.Nimi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nimi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nimi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ahinta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ahinta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ahinta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kuva, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Kuva, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kuva, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KuvaPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KuvaPath, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KuvaPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TilausDB1/Views/Tuotteet/Index.cshtml
@model PagedList.IPagedList<TilausDB1.Models.Tuotteet>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

@section scripts {
    <script type="text/javascript">
        $("#singleSelectedCategoryID").on("change", function () {
            var selValue = $("#singleSelectedCategoryID").val();
            document.getElementById("ProductCategory").value = selValue;
        });
    </script>
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Tuotteet", FormMethod.Get))
{
    <div class="input-group">
        <p class="px-1">@Html.Label("Find by name:")</p>
        <p class="px-1">@Html.TextBox("SearchString1", ViewBag.currentFilter1 as string, new { @class = "form-control" })</p>
        <p class="px-1">@Html.Label("Find by Product Category:")</p>
        <p class="px-1">@Html.Hidden("ProductCategory", ViewBag.currentFilter1 as string, new { @id = "ProductCategory", @class = "form-control" })</p>
        <p class="px-1">@Html.DropDownList("CategoryID", null, htmlAttributes: new { @id = "singleSelectedCategoryID", @class = "form-control" })</p>
        <p class="px-1"><input type="submit" value="Search" class="form-control" /></p>
    </div>
}
<div class="container-md mt-3 border">
    <table class="table-responsive-lg">
        <tr>
            <th>@Html.ActionLink("Tuotteen nimi", "Index", new { sortOrder = ViewBag.ProductNameSortParm, currentFilter1 = ViewBag.currentFilter1, currentProductCategory = ViewBag.currentProductCategory })</th>
            <th>@Html.ActionLink("Ahinta", "Index", new { sortOrder = ViewBag.UnitPriceSortParm, currentFilter1 = ViewBag.currentFilter1, currentProductCategory = ViewBag.currentProductCategory })</th>
            <th hidden>Kuva</th>
            <th>KategoriaNimi</th>
            <th>Nimi</th>
            <th>Nimi</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nimi)</td>
                <td>@Html.DisplayFor(modelItem => item.Ahinta)</td>
                <td hidden>@Html.DisplayFor(modelItem => item.Kuva)</td>
                @*<td>@Html.DisplayFor(modelItem => item.KuvaPath)</td>*@
                <td>@Html.DisplayFor(modelItem => item.Kategoriat.KategoriaNimi)</td>
                <td>@Html.DisplayFor(modelItem => item.Tuotteet1.Nimi)</td>
                <td>@Html.DisplayFor(modelItem => item.Tuotteet2.Nimi)</td>
                <td>
                    <a class="btn btn-primary" href="~/Tuotteet/Edit/@item.TuoteID">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a class="btn btn-primary" href="~/Tuotteet/Details/@item.TuoteID">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-lg" viewBox="0 0 16 16">
                            <path d="m9.708 6.075-3.024.379-.108.502.595.108c.387.093.464.232.38.619l-.975 4.577c-.255 1.183.14 1.74 1.067 1.74.72 0 1.554-.332 1.933-.789l.116-.549c-.263.232-.65.325-.905.325-.363 0-.494-.255-.402-.704l1.323-6.208Zm.091-2.755a1.32 1.32 0 1 1-2.64 0 1.32 1.32 0 0 1 2.64 0Z" />
                        </svg>
                    </a>
                    <a class="btn btn-primary" href="~/Tuotteet/Delete/@item.TuoteID">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.TuoteID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.TuoteID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.TuoteID })*@
                </td>
            </tr>
        }

    </table>
</div>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter1 = ViewBag.currentFilter1, currentProductCategory = ViewBag.currentProductCategory }))

TilausDB1/Views/Tuotteet/Index2.cshtml
@{
    ViewBag.Title = "Index2";
}
    <div class="container-fluid">

        <h2>Tuotteet</h2>
        <div class="row">
            @foreach (TilausDB1.Models.Tuotteet item in Model)
            {
                <div class="col-lg-3">
                    <div class="card mb-3">
                        <h3 class="card-header">    @item.Nimi</h3>
                        <div class="card-body">
                            <h5 class="card-title"> €   @item.Ahinta</h5>
                            <h6 class="card-subtitle text-muted">    @item.TuoteID</h6>
                        </div>
                        <img style="height:200px; width:100%; display: block;" src="@item.Kuva" alt="@item.Kuva">
                        <div class="card-body">
                            <p class="card-text">Kaikki tuotteemme ovat kotimaisia.</p>
                        </div>
                        <div class="card-footer text-muted">
                            2 days ago
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>

TilausDB1/Views/Tuotteet/Index3.cshtml
@model PagedList.IPagedList<TilausDB1.Models.Tuotteet>

@{
    ViewBag.Title = "Index";
}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
          crossorigin="anonymous">

<h2>Index</h2>
<p>@Html.ActionLink("Create New", "Create")</p>
<table class="table">
    <thead>
        <tr>
            <th >TuoteID</th>
            <th>Nimi</th>
            <th>Ahinta</th>
            <th>Kuva</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (TilausDB1.Models.Tuotteet item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.TuoteID)</td>
                <td>@Html.DisplayFor(modelItem => item.Nimi)</td>
                <td>@Html.DisplayFor(modelItem => item.Ahinta)</td>
                <td>@Html.DisplayFor(modelItem => item.Kuva)</td>
                <td>

                    <a class="btn btn-primary" href="~/Tuotteet/Edit/@item.TuoteID">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a class="btn btn-primary" href="~/Tuotteet/Details/@item.TuoteID">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-lg" viewBox="0 0 16 16">
                            <path d="m9.708 6.075-3.024.379-.108.502.595.108c.387.093.464.232.38.619l-.975 4.577c-.255 1.183.14 1.74 1.067 1.74.72 0 1.554-.332 1.933-.789l.116-.549c-.263.232-.65.325-.905.325-.363 0-.494-.255-.402-.704l1.323-6.208Zm.091-2.755a1.32 1.32 0 1 1-2.64 0 1.32 1.32 0 0 1 2.64 0Z" />
                        </svg>
                    </a>
                    <a class="btn btn-primary" href="~/Tuotteet/Delete/@item.TuoteID">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>